# Generated by Django 2.1.7 on 2019-05-22 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dmenu_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmenu',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
